// Auth Action Types
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_REGISTER_START = "AUTH_REGISTER_START";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";

// Products Action Types
export const PRODUCTS_SET_LOADING = "PRODUCTS_SET_LOADING";
export const PRODUCTS_SET_ERROR = "PRODUCTS_SET_ERROR";
export const PRODUCTS_SET_PRODUCTS = "PRODUCTS_SET_PRODUCTS";
export const PRODUCTS_FILTER_BY_CATEGORY = "PRODUCTS_FILTER_BY_CATEGORY";
export const PRODUCTS_SEARCH = "PRODUCTS_SEARCH";
export const PRODUCTS_CLEAR_FILTERS = "PRODUCTS_CLEAR_FILTERS";

// Users Action Types
export const USERS_SET_LOADING = "USERS_SET_LOADING";
export const USERS_SET_ERROR = "USERS_SET_ERROR";
export const USERS_SET_USERS = "USERS_SET_USERS";
export const USERS_ADD_USER = "USERS_ADD_USER";
export const USERS_UPDATE_USER = "USERS_UPDATE_USER";
export const USERS_DELETE_USER = "USERS_DELETE_USER";
