// Mock products data
export const mockProducts = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    price: 999.99,
    description: "En yeni iPhone modeli, gelişmiş kamera ve performans",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=iPhone+15+Pro",
    stock: 50,
    rating: 4.8,
  },
  {
    id: 2,
    name: "MacBook Air M2",
    price: 1199.99,
    description: "Güçlü M2 çipli ultra ince dizüstü bilgisayar",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=MacBook+Air+M2",
    stock: 30,
    rating: 4.9,
  },
  {
    id: 3,
    name: "AirPods Pro",
    price: 249.99,
    description: "Aktif gürültü engelleme özellikli kablosuz kulaklık",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=AirPods+Pro",
    stock: 100,
    rating: 4.7,
  },
  {
    id: 4,
    name: "Nike Air Max",
    price: 129.99,
    description: "Rahat ve şık spor ayakkabı",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Nike+Air+Max",
    stock: 75,
    rating: 4.5,
  },
  {
    id: 5,
    name: "Samsung 4K TV",
    price: 799.99,
    description: "55 inç 4K Ultra HD Smart TV",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Samsung+4K+TV",
    stock: 25,
    rating: 4.6,
  },
  {
    id: 6,
    name: "Adidas Hoodie",
    price: 59.99,
    description: "Konforlu ve şık kapüşonlu sweatshirt",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Adidas+Hoodie",
    stock: 60,
    rating: 4.4,
  },
  {
    id: 7,
    name: "PlayStation 5",
    price: 499.99,
    description: "Son nesil oyun konsolu",
    category: "Gaming",
    image: "https://via.placeholder.com/300x300?text=PlayStation+5",
    stock: 15,
    rating: 4.9,
  },
  {
    id: 8,
    name: "Coffee Maker",
    price: 89.99,
    description: "Otomatik kahve makinesi",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Coffee+Maker",
    stock: 40,
    rating: 4.3,
  },
  {
    id: 9,
    name: "Wireless Mouse",
    price: 29.99,
    description: "Ergonomik tasarım kablosuz mouse",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Wireless+Mouse",
    stock: 120,
    rating: 4.2,
  },
  {
    id: 10,
    name: "Gaming Chair",
    price: 199.99,
    description: "Konforlu oyuncu koltuğu",
    category: "Gaming",
    image: "https://via.placeholder.com/300x300?text=Gaming+Chair",
    stock: 35,
    rating: 4.6,
  },
  {
    id: 11,
    name: "Bluetooth Speaker",
    price: 79.99,
    description: "Taşınabilir kablosuz hoparlör",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Bluetooth+Speaker",
    stock: 85,
    rating: 4.4,
  },
  {
    id: 12,
    name: "Running Shoes",
    price: 89.99,
    description: "Hafif ve dayanıklı koşu ayakkabısı",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Running+Shoes",
    stock: 65,
    rating: 4.3,
  },
];

// Product categories
export const productCategories = [
  "All",
  "Electronics",
  "Fashion",
  "Gaming",
  "Home",
];

export default mockProducts;
