// Mock users data
export const mockUsers = [
  {
    id: 1,
    username: "admin",
    email: "admin@shopistire.com",
    password: "123456",
    firstName: "Yönetici",
    lastName: "Kullanıcı",
    role: "admin",
  },
  {
    id: 2,
    username: "mehmetozkan",
    email: "mehmet@shopistire.com",
    password: "123456",
    firstName: "Mehmet",
    lastName: "Özkan",
    role: "user",
  },
  {
    id: 3,
    username: "aysegunes",
    email: "ayse@shopistire.com",
    password: "123456",
    firstName: "Ayşe",
    lastName: "Güneş",
    role: "user",
  },
  {
    id: 4,
    username: "muslumcelik",
    email: "muslum@shopistire.com",
    password: "123456",
    firstName: "Müslüm",
    lastName: "Çelik",
    role: "user",
  },
  {
    id: 5,
    username: "zeynepsahin",
    email: "zeynep@shopistire.com",
    password: "123456",
    firstName: "Zeynep",
    lastName: "Şahin",
    role: "user",
  },
  {
    id: 6,
    username: "emrekucuk",
    email: "emre@shopistire.com",
    password: "123456",
    firstName: "Emre",
    lastName: "Küçük",
    role: "user",
  },
  {
    id: 7,
    username: "semaozturk",
    email: "sema@shopistire.com",
    password: "123456",
    firstName: "Sema",
    lastName: "Öztürk",
    role: "user",
  },
  {
    id: 8,
    username: "burakgul",
    email: "burak@shopistire.com",
    password: "123456",
    firstName: "Burak",
    lastName: "Gül",
    role: "user",
  },
];

export default mockUsers;
